### PR TITLE
Various Options Improvements

### LINKED ISSUE #222: More detailed options screen
**Description**

Major Hitlist for this includes:
- [x] Volume
- [ ] PvP Toggles

### PR DESCRIPTION
**Pull request by josephbmanley**
image

### Summary
- Allow you to open and make option changes in game
- Moves options into a more modular system where it is separated into tabs
- Adds simple Sound options page where you can affect the volume of the master bus
- **NEW** All options save upon exiting options screen

### Testing
Run the game, once in a singleplayer or multiplayer match then press `ESC` then `Options`

[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) Just in case, yes it has.

Closes #222 

---

As a note this PR does not currently involve the PvP toggle of #222  ~~May require some polish before merging, like UI art for the Sound page for example.~~
image

~~I would also like to get a central options saving system in place before merging if possible, though that would probably qualify as a stretch goal.~~

### CODE REVIEW

**Comment by josephbmanley** [comment]
Update: It's pretty now
image

**Comment by josephbmanley** [comment]
Only thing that is currently not saved is the keybindings... Staring at that code right right now...

**Comment by josephbmanley** [comment]
I am very close to getting keybinds to save. Hopefully be in tonight...

**Comment by josephbmanley** [comment]
Keybinds save!!!! :open_mouth:

**Review by Elginive — APPROVED** [review]
Working as intended, in game Keybinds & Volume Controls. Saves States in-between sessions.

**Pull request merged**
