### PR TITLE
Word Filtering & Blacklist

### LINKED ISSUE #292: Name cleaning
**Description**

Currently no check as to what players name themselves.

**Due tomorrow at 1PM**

### LINKED ISSUE #293: Beginning game clarification
**Description**

Need to polish how we push the players into playing the game, giving them clear goals and things to look for.

1. Create better NPC dialogue to push them towards the bow shrine and first dungeon.
2. Have Spirit NPC at start explain parts of the game, such as what to expect at demo and for actual game.

### PR DESCRIPTION
**Pull request by josephbmanley**
**DEPENDS ON #287**
---

image
image

### Summary
Certain words and phrases will now be censored by default.  This is done by including a blacklist containing notable words for english, french, and spanish that are searched for. Upon detection the entire name is censored. This option is togglable in the options menu.

As a note, this is done on client and server. So it would be possible in the future to allow the client to add words on their end if there is certain things they would not like to see.

It would also be easy to use the same feature in a chat system.

Added utility functions:
- `global.value_in_blacklist(value) -> bool`
- `global.filter_value(value) -> String`

### Testing
Start a multiplayer match and connect with a name that should be filtered.

[**Has this been tested in multiplayer?**](https://github.com/loudsmilestudios/TetraForce/wiki/How-to-test-multiplayer) *yes*

Closes #292

### CODE REVIEW

**Comment by Nodding** [comment]
Out of curiosity how easily would it be to add other languages?

**Comment by josephbmanley** [comment]
> Out of curiosity how easily would it be to add other languages?

The phrases would just need to be added to blacklist.txt

**Review by Elginive — APPROVED** [review]
Aw great, now I can't ^%%& swear in my own game. I guess this works as intended, so good to merge.

**Review by Nodding — COMMENTED** [review]
Nice. In future we may need to add more languages.

**Pull request merged**
